version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/

  hunspell:
    image: insekticid/elasticsearch-hunspell
    build: .
    depends_on:
      - elasticsearch
    networks:
      - elastic
    volumes:
      - hunspell-volume:/usr/share/elasticsearch/config/hunspell/
    entrypoint: sh  

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.3
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro:0.7.3
    ports:
      - "9000:9000"
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
    
volumes:
  hunspell-volume: